apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapplication
  labels:
    {{- include "flaskapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flaskapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flaskapp.selectorLabels" . | nindent 8 }}
    spec:

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
              
          resources:
            requests:
               memory: {{ .Values.memoryRequest | quote }}
               cpu: {{ .Values.cpuRequest | quote }}
            limits:
               cpu: {{ .Values.cpuLimit | quote }}
               memory: {{ .Values.memoryLimit | quote }}      
