apiVersion: v1
kind: Service
metadata:
  name: flaskapplication
spec:
  type: {{ .Values.servicetype }}
  ports:
    - port: {{ .Values.serviceport }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flaskapp.selectorLabels" . | nindent 4 }}
